# Generated by Django 6.0.1 on 2026-01-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="created_by",
        ),
    ]
