# Generated by Django 6.0.1 on 2026-01-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_cost"),
        ("customers", "0001_initial"),
        ("leads", "0003_alter_lead_email_alter_lead_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="contracts.contract",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="leads.lead",
            ),
        ),
    ]
