# Generated by Django 6.0.1 on 2026-01-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ad_created_by"),
        ("products", "0005_alter_product_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ads",
                to="products.product",
            ),
        ),
    ]
