# Generated by Django 6.0.1 on 2026-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
