# Generated by Django 6.0.1 on 2026-01-31 10:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_email_alter_lead_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
