# Generated by Django 6.0.1 on 2026-01-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("products", "0005_alter_product_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="ad",
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
