# Generated by Django 6.0.1 on 2026-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_remove_contract_ad_contract_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
