# Generated by Django 6.0.1 on 2026-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
